language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- npm run lint
- npm run lint:styles
- npm run test-headless
- npm run build --prod --base-href https://ngramprabhu.github.io/travisdemo/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/travisdemo
  on:
    branch: master