language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
jobs:
  include:
    - stage: "Tests"             # naming the Tests stage
      name: "Code Lint"          # names the first Tests stage job
      script: npm run lint
    - script: npm run lint:styles
      name: "CSS Style Lint"     # names the second Tests stage job
    - script: npm run test-headless
      name: "Unit Tests"         # names the Third Tests stage job
    - stage: "Build"
      name: "Build"
      script: ng build --prod --base-href https://ngramprabhu.github.io/travisdemo/
    - stage: "Deployment"
      name: "Deploy to GitHub Pages"
      script: ./deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/travisdemo
        on:
          branch: master